### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Subere** [Tiim/Android-Markdown-Widget#1]
Hey Tim.

This widget looks very promising, however I can't find an .apk. Neither here nor at F-Droid or in the Play Store. At [GitLab](https://gitlab.com/fdroid/rfp/-/issues/2085) I read that your widget should be published on F-Droid, but a donation is missing?

Do you still plan to release the app? I would be very happy about it.

Thanks in advance

**Comment by Tiim** [comment]
The app is not on the Play Store, and it is not on F-Droid yet. I have submitted a request for packaging for F-Droid (the link you posted), but it seems they have not gotten around to do that yet.

I guess currently the only option is to manually compile it, since I don't have the apk hosted anywhere for now. 

I will keep this issue open until I get around to providing an apk either on F-Droid or here on github.

**Comment by Subere** [comment]
Thanks for the quick reply! I would be very happy about a release.

**Comment by ooker777** [comment]
Hmm, but why can't you compile it and post the apk in here?

**Comment by Tiim** [comment]
The apk for the current and every future release is now available [here](https://github.com/Tiim/Android-Markdown-Widget/releases/tag/v0.1.1) :)

**Comment by ooker777** [comment]
I download it and it cannot be installed. It only says the file is corrupt. I'm on android 7

**Comment by Tiim** [comment]
@ooker777 I did not provide a signed apk, thats why it didn't work. 
The [latest release](https://github.com/Tiim/Android-Markdown-Widget/releases/tag/v0.1.4) now also includes a signed version which works for me.

**Comment by ooker777** [comment]
I install successfully. However it still doesn't work seamlessly:
- When I choose to open with default markdown app (I use Markor), it tells me that the path is not absolute so it cannot open it. Here is it detailed info: https://github.com/gsantner/markor/discussions/1381
- I cannot open it with Obsidian
- It cannot scroll down to show more text

**Comment by Tiim** [comment]
Since this is not about the download anymore can you create a new issue for that?

**Comment by ooker777** [comment]
Sure. Thanks for your help
