### ISSUE TITLE
Can't select .md files to add the widget

### ISSUE THREAD

**Issue by guihasparyk** [Tiim/Android-Markdown-Widget#14]
I've installed the app trough F-Droid and none of whatever '.md' files are clickable when selecting the files to create the widget.

Is it just me an and my phone or everyone else is experimenting the same issue?

**Comment by teodor-a** [comment]
Following because I experience this too. The files are all grayed out in the file browser.

**Comment by Tiim** [comment]
Please share what phone you are using and what version of Android. This may relate to storage permissions not being properly requested for some Android versions.

**Comment by teodor-a** [comment]
> Please share what phone you are using and what version of Android. This may relate to storage permissions not being properly requested for some Android versions.

Samsung galaxy S8
Android 9
App downloaded from F-droid

**Comment by guihasparyk** [comment]
Huawei P20 Lite
ANE-LX1 (Android 9.1.0.368)
Download from F-Droid.

**Comment by evergreen-tm** [comment]
Seeing this as well on a OnePlus 8T running Android 13 (LMODroid), both downloaded from F-Droid and the release from github.

**Comment by daschfg** [comment]
Same issue on Android 8 here.

I poked around a bit... My guess is that older Android SDKs are missing the MIME-type "text/markdown".
What worked for me was changing `type` on this line:
https://github.com/Tiim/Android-Markdown-Widget/blob/bf9849d79ca48171ce700b758f26da3b92416b71/app/src/main/java/ch/tiim/markdown_widget/MarkdownFileWidgetConfigureActivity.kt#L40
from `"text/markdown"` to `"*/*"`.

Unfortunately, other stricter variants like `"text/*"` don't work for \*.md-files for me as well.

Downside: Now a user can select any file type, which leads to funny results when displaying these files.

**Comment by guihasparyk** [comment]
That's good to hear you find a workaround @daschfg .

Can you tell how do you did that? How you managed to view and edit code inside the app already installed?

**Comment by daschfg** [comment]
Sorry, no, I didn't modify the installed app.
I cloned the code from here, recompiled it in Android Studio with my modification and installed the resulting new APK.

@Tiim: Would you be willing to accept a pull request on this?
I would further research how this could maybe get detected in advance, so that the workaround would hopefully not affect newer Android versions.

**Comment by Tiim** [comment]
Hi @daschfg thanks for looking into this. I will definitely have a look at your pull request!

**Comment by opk12** [comment]
Another workaround is to install [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/). When the widget prompts to open a file, select Intent Intercept, change the two occurrences of `text/markdown`, click at the bottom to re-send the intent. This is useful for those using the widget from F-droid, which is still at 0.1.4 (#17).
