### ISSUE TITLE
Doesn't update when md file changes

### ISSUE THREAD

**Issue by tjthejuggler** [Tiim/Android-Markdown-Widget#7]
If I change the .md file it doesn't show in the widget. I have to delete and recreate the widget to see the new text.

**Comment by Tiim** [comment]
The widget will update eventually (about every 30min). To manually update it, you can resize it as well.

It would be nice to somehow subscribe to file changes to directly update the widget when the file gets modified, but I currently have no idea how to do that.

**Comment by tjthejuggler** [comment]
Thanks for the response. Youre right, it updated with time, i didnt know about the resize trick. I have noticed that it still occasionally goed blank for a little while, but not often, and i dont know why.
